name: main
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:

    runs-on: self-hosted

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Unit tests
      run: npm run test
