name: main
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:

    runs-on: self-hosted

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Unit tests
      run: npm run test

  build:
    needs: test
    runs-on: self-hosted

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: /usr/bin/rsync -r ./build/ ${SERVER_UBUNTU}:${SERVER_PATH_UBUNTU}. --exclude-from="exclude.build"
        path: './dist/vps'

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Dowload artifact
      uses: actions/download-artifact@v2
      with:
        name: /usr/bin/rsync -r ./build/ ${SERVER_UBUNTU}:${SERVER_PATH_UBUNTU}. --exclude-from="exclude.build"
        path: './build'
